import type { Agent, Listing, Location, InquiryRecord } from "./types";

export const mockLocations: Location[] = [
  { id: "loc-kinoo", name: "Kinoo", county: "Kiambu" },
  { id: "loc-kikuyu", name: "Kikuyu", county: "Kiambu" },
  { id: "loc-sigona", name: "Sigona", county: "Kiambu" },
  { id: "loc-zambezi", name: "Zambezi", county: "Kiambu" },
  { id: "loc-regen", name: "Regen", county: "Kiambu" },
];

export const mockAgents: Agent[] = [
  {
    id: "agent-1",
    fullName: "James Mwangi",
    phoneNumber: "+254712345678",
    whatsappNumber: "254712345678",
  },
  {
    id: "agent-2",
    fullName: "Grace Wairimu",
    phoneNumber: "+254722334455",
    whatsappNumber: "254722334455",
  },
];

const photo = (id: string, url: string, sortOrder: number) => ({ id, url, sortOrder });

// Unsplash photos for now. TODO: SUPABASE — replace with Supabase Storage URLs.
const UNSPLASH = {
  bedsit: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200",
  apt1: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200",
  apt2: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200",
  apt3: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200",
  apt4: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1200",
  apt5: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=1200",
  apt6: "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=1200",
  apt7: "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=1200",
  kitchen: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200",
  bedroom: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200",
};

export const mockListings: Listing[] = [
  {
    id: "lst-1",
    title: "Bright Bedsitter in Kinoo with Water Backup",
    description:
      "A compact, sunlit bedsitter perfect for young professionals. Tiled floors, modern fittings, and 24/7 water supply with backup tanks. Walking distance to Kinoo stage.",
    listingType: "rent",
    status: "available",
    bedrooms: 0,
    bathrooms: 1,
    price: 9500,
    deposit: 9500,
    location: mockLocations[0],
    addressDetail: "Off Kinoo Road, near Acacia Plaza",
    latitude: -1.2548,
    longitude: 36.6814,
    amenities: ["water_backup", "cctv", "parking"],
    agent: mockAgents[0],
    isFeatured: true,
    photos: [photo("p1", UNSPLASH.bedsit, 0), photo("p2", UNSPLASH.bedroom, 1)],
    createdAt: "2025-06-20T09:00:00Z",
  },
  {
    id: "lst-2",
    title: "Spacious 2-Bedroom Apartment in Kikuyu",
    description:
      "Modern 2-bedroom apartment with master ensuite, fitted kitchen, and ample parking. Quiet, gated estate with backup generator and lift.",
    listingType: "rent",
    status: "available",
    bedrooms: 2,
    bathrooms: 2,
    price: 35000,
    deposit: 35000,
    location: mockLocations[1],
    addressDetail: "Kikuyu Town, off Southern Bypass",
    latitude: -1.2461,
    longitude: 36.6628,
    amenities: ["ensuite", "parking", "water_backup", "lift", "cctv"],
    agent: mockAgents[1],
    isFeatured: true,
    photos: [
      photo("p3", UNSPLASH.apt1, 0),
      photo("p4", UNSPLASH.kitchen, 1),
      photo("p5", UNSPLASH.bedroom, 2),
    ],
    createdAt: "2025-06-25T10:00:00Z",
  },
  {
    id: "lst-3",
    title: "Modern 1-Bedroom Apartment with Solar",
    description:
      "Newly built 1-bedroom with solar water heating and high-speed fibre ready. Spacious balcony with views of the Ngong escarpment.",
    listingType: "rent",
    status: "available",
    bedrooms: 1,
    bathrooms: 1,
    price: 22000,
    deposit: 22000,
    location: mockLocations[2],
    addressDetail: "Sigona, off Waiyaki Way",
    latitude: -1.2336,
    longitude: 36.6489,
    amenities: ["solar", "parking", "water_backup", "cctv"],
    agent: mockAgents[0],
    isFeatured: false,
    photos: [photo("p6", UNSPLASH.apt2, 0), photo("p7", UNSPLASH.apt3, 1)],
    createdAt: "2025-06-18T08:00:00Z",
  },
  {
    id: "lst-4",
    title: "3-Bedroom Family Apartment in Zambezi",
    description:
      "Large 3-bedroom apartment ideal for families. Master ensuite, DSQ, fitted wardrobes, and secure gated community with CCTV and 24/7 guards.",
    listingType: "rent",
    status: "available",
    bedrooms: 3,
    bathrooms: 3,
    price: 55000,
    deposit: 55000,
    location: mockLocations[3],
    addressDetail: "Zambezi, near the shopping centre",
    latitude: -1.2197,
    longitude: 36.6325,
    amenities: ["ensuite", "parking", "water_backup", "cctv", "lift", "solar"],
    agent: mockAgents[1],
    isFeatured: true,
    photos: [
      photo("p8", UNSPLASH.apt4, 0),
      photo("p9", UNSPLASH.apt5, 1),
      photo("p10", UNSPLASH.kitchen, 2),
    ],
    createdAt: "2025-06-15T11:00:00Z",
  },
  {
    id: "lst-5",
    title: "Affordable Bedsitter in Kikuyu",
    description: "Budget-friendly bedsitter with shared parking and constant water supply.",
    listingType: "rent",
    status: "let",
    bedrooms: 0,
    bathrooms: 1,
    price: 7500,
    deposit: 7500,
    location: mockLocations[1],
    addressDetail: "Kikuyu, near Thogoto",
    latitude: -1.2522,
    longitude: 36.6611,
    amenities: ["water_backup"],
    agent: mockAgents[0],
    isFeatured: false,
    photos: [photo("p11", UNSPLASH.apt6, 0)],
    createdAt: "2025-05-30T08:00:00Z",
  },
  {
    id: "lst-6",
    title: "Executive 2-Bedroom in Sigona",
    description:
      "Premium finishes, en-suite master, lift access, and rooftop terrace. Backup power and water.",
    listingType: "rent",
    status: "available",
    bedrooms: 2,
    bathrooms: 2,
    price: 42000,
    deposit: 42000,
    location: mockLocations[2],
    addressDetail: "Sigona Golf Estate area",
    latitude: -1.231,
    longitude: 36.65,
    amenities: ["ensuite", "parking", "water_backup", "lift", "cctv", "solar"],
    agent: mockAgents[1],
    isFeatured: false,
    photos: [photo("p12", UNSPLASH.apt7, 0), photo("p13", UNSPLASH.bedroom, 1)],
    createdAt: "2025-06-10T14:00:00Z",
  },
];

export const mockInquiries: InquiryRecord[] = [
  {
    id: "inq-1",
    listingId: "lst-2",
    agentId: "agent-2",
    name: "Peter Kamau",
    phoneNumber: "+254700111222",
    message: "Is the 2-bedroom in Kikuyu still available? Looking to move in July.",
    preferredMoveIn: "2025-07-15",
    contactChannel: "form",
    status: "new",
    createdAt: "2025-06-28T09:30:00Z",
  },
  {
    id: "inq-2",
    listingId: "lst-1",
    agentId: "agent-1",
    name: "Mary Achieng",
    phoneNumber: "+254711333444",
    message: "Can I view this weekend?",
    preferredMoveIn: "2025-07-01",
    contactChannel: "whatsapp",
    status: "contacted",
    createdAt: "2025-06-27T15:00:00Z",
  },
  {
    id: "inq-3",
    listingId: "lst-4",
    agentId: "agent-2",
    name: "David Otieno",
    phoneNumber: "+254733555666",
    message: null,
    preferredMoveIn: null,
    contactChannel: "call",
    status: "new",
    createdAt: "2025-06-29T11:20:00Z",
  },
];
