/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CaretakerRouteImport } from './routes/caretaker'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaretakerIndexRouteImport } from './routes/caretaker.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as CaretakerReportsRouteImport } from './routes/caretaker.reports'
import { Route as CaretakerListingsRouteImport } from './routes/caretaker.listings'
import { Route as AdminPhotosRouteImport } from './routes/admin.photos'
import { Route as AdminMaintenanceRouteImport } from './routes/admin.maintenance'
import { Route as AdminInquiriesRouteImport } from './routes/admin.inquiries'
import { Route as AdminCaretakersRouteImport } from './routes/admin.caretakers'
import { Route as AdminListingsIndexRouteImport } from './routes/admin.listings.index'
import { Route as AdminListingsNewRouteImport } from './routes/admin.listings.new'
import { Route as AdminListingsIdEditRouteImport } from './routes/admin.listings.$id.edit'

const CaretakerRoute = CaretakerRouteImport.update({
  id: '/caretaker',
  path: '/caretaker',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaretakerIndexRoute = CaretakerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaretakerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CaretakerReportsRoute = CaretakerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => CaretakerRoute,
} as any)
const CaretakerListingsRoute = CaretakerListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => CaretakerRoute,
} as any)
const AdminPhotosRoute = AdminPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaintenanceRoute = AdminMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCaretakersRoute = AdminCaretakersRouteImport.update({
  id: '/caretakers',
  path: '/caretakers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsIndexRoute = AdminListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsNewRoute = AdminListingsNewRouteImport.update({
  id: '/listings/new',
  path: '/listings/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsIdEditRoute = AdminListingsIdEditRouteImport.update({
  id: '/listings/$id/edit',
  path: '/listings/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/caretaker': typeof CaretakerRouteWithChildren
  '/admin/caretakers': typeof AdminCaretakersRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/photos': typeof AdminPhotosRoute
  '/caretaker/listings': typeof CaretakerListingsRoute
  '/caretaker/reports': typeof CaretakerReportsRoute
  '/listings/$id': typeof ListingsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/caretaker/': typeof CaretakerIndexRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/admin/listings/': typeof AdminListingsIndexRoute
  '/admin/listings/$id/edit': typeof AdminListingsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/caretakers': typeof AdminCaretakersRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/photos': typeof AdminPhotosRoute
  '/caretaker/listings': typeof CaretakerListingsRoute
  '/caretaker/reports': typeof CaretakerReportsRoute
  '/listings/$id': typeof ListingsIdRoute
  '/admin': typeof AdminIndexRoute
  '/caretaker': typeof CaretakerIndexRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/admin/listings': typeof AdminListingsIndexRoute
  '/admin/listings/$id/edit': typeof AdminListingsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/caretaker': typeof CaretakerRouteWithChildren
  '/admin/caretakers': typeof AdminCaretakersRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/photos': typeof AdminPhotosRoute
  '/caretaker/listings': typeof CaretakerListingsRoute
  '/caretaker/reports': typeof CaretakerReportsRoute
  '/listings/$id': typeof ListingsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/caretaker/': typeof CaretakerIndexRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/admin/listings/': typeof AdminListingsIndexRoute
  '/admin/listings/$id/edit': typeof AdminListingsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/caretaker'
    | '/admin/caretakers'
    | '/admin/inquiries'
    | '/admin/maintenance'
    | '/admin/photos'
    | '/caretaker/listings'
    | '/caretaker/reports'
    | '/listings/$id'
    | '/admin/'
    | '/caretaker/'
    | '/admin/listings/new'
    | '/admin/listings/'
    | '/admin/listings/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/caretakers'
    | '/admin/inquiries'
    | '/admin/maintenance'
    | '/admin/photos'
    | '/caretaker/listings'
    | '/caretaker/reports'
    | '/listings/$id'
    | '/admin'
    | '/caretaker'
    | '/admin/listings/new'
    | '/admin/listings'
    | '/admin/listings/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/caretaker'
    | '/admin/caretakers'
    | '/admin/inquiries'
    | '/admin/maintenance'
    | '/admin/photos'
    | '/caretaker/listings'
    | '/caretaker/reports'
    | '/listings/$id'
    | '/admin/'
    | '/caretaker/'
    | '/admin/listings/new'
    | '/admin/listings/'
    | '/admin/listings/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CaretakerRoute: typeof CaretakerRouteWithChildren
  ListingsIdRoute: typeof ListingsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/caretaker': {
      id: '/caretaker'
      path: '/caretaker'
      fullPath: '/caretaker'
      preLoaderRoute: typeof CaretakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caretaker/': {
      id: '/caretaker/'
      path: '/'
      fullPath: '/caretaker/'
      preLoaderRoute: typeof CaretakerIndexRouteImport
      parentRoute: typeof CaretakerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caretaker/reports': {
      id: '/caretaker/reports'
      path: '/reports'
      fullPath: '/caretaker/reports'
      preLoaderRoute: typeof CaretakerReportsRouteImport
      parentRoute: typeof CaretakerRoute
    }
    '/caretaker/listings': {
      id: '/caretaker/listings'
      path: '/listings'
      fullPath: '/caretaker/listings'
      preLoaderRoute: typeof CaretakerListingsRouteImport
      parentRoute: typeof CaretakerRoute
    }
    '/admin/photos': {
      id: '/admin/photos'
      path: '/photos'
      fullPath: '/admin/photos'
      preLoaderRoute: typeof AdminPhotosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maintenance': {
      id: '/admin/maintenance'
      path: '/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AdminMaintenanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/caretakers': {
      id: '/admin/caretakers'
      path: '/caretakers'
      fullPath: '/admin/caretakers'
      preLoaderRoute: typeof AdminCaretakersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings/': {
      id: '/admin/listings/'
      path: '/listings'
      fullPath: '/admin/listings/'
      preLoaderRoute: typeof AdminListingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings/new': {
      id: '/admin/listings/new'
      path: '/listings/new'
      fullPath: '/admin/listings/new'
      preLoaderRoute: typeof AdminListingsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings/$id/edit': {
      id: '/admin/listings/$id/edit'
      path: '/listings/$id/edit'
      fullPath: '/admin/listings/$id/edit'
      preLoaderRoute: typeof AdminListingsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCaretakersRoute: typeof AdminCaretakersRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminMaintenanceRoute: typeof AdminMaintenanceRoute
  AdminPhotosRoute: typeof AdminPhotosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminListingsNewRoute: typeof AdminListingsNewRoute
  AdminListingsIndexRoute: typeof AdminListingsIndexRoute
  AdminListingsIdEditRoute: typeof AdminListingsIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCaretakersRoute: AdminCaretakersRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminMaintenanceRoute: AdminMaintenanceRoute,
  AdminPhotosRoute: AdminPhotosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminListingsNewRoute: AdminListingsNewRoute,
  AdminListingsIndexRoute: AdminListingsIndexRoute,
  AdminListingsIdEditRoute: AdminListingsIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CaretakerRouteChildren {
  CaretakerListingsRoute: typeof CaretakerListingsRoute
  CaretakerReportsRoute: typeof CaretakerReportsRoute
  CaretakerIndexRoute: typeof CaretakerIndexRoute
}

const CaretakerRouteChildren: CaretakerRouteChildren = {
  CaretakerListingsRoute: CaretakerListingsRoute,
  CaretakerReportsRoute: CaretakerReportsRoute,
  CaretakerIndexRoute: CaretakerIndexRoute,
}

const CaretakerRouteWithChildren = CaretakerRoute._addFileChildren(
  CaretakerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CaretakerRoute: CaretakerRouteWithChildren,
  ListingsIdRoute: ListingsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
